# Site settings
title: "CyberNotes"
author: "Oussama Ben Moussa"
description: "Pentester et passionné par la cybersécurité, je partage ici mes découvertes, tutoriels et analyses de vulnérabilités."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://obenmoussaa.github.io" # the base hostname & protocol

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima # You can change this or use a custom theme

# Collections
collections:
  tutorials:
    output: true
    permalink: /tutorials/:path/
  web:
    output: true
    permalink: /web/:path/

# Default front matter settings
defaults:
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "web"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Social links (if you want to include them)
github_username: obenmoussaa
